DROP TABLE PRODUCTS IF EXISTS;

CREATE TABLE PRODUCTS (
  ID VARCHAR(25) PRIMARY KEY,
  NAME VARCHAR(50),
  DESCRIPTION  VARCHAR(250),
  UNIT_PRICE DECIMAL,
  MANUFACTURER VARCHAR(50),
  CATEGORY VARCHAR(50),
  CONDITION VARCHAR(50),
  UNITS_IN_STOCK BIGINT,
  UNITS_IN_ORDER BIGINT,
  DISCONTINUED BOOLEAN,
  IMAGE_SRC VARCHAR(250)
);

DROP TABLE DISHES IF EXISTS;

CREATE TABLE DISHES (
  ID VARCHAR(25) PRIMARY KEY,
  NAME VARCHAR(50),
  DESCRIPTION  VARCHAR(250),
  WEIGHT INT,
  UNIT_PRICE DECIMAL,
  CATEGORY VARCHAR(50),
  WEEK_SERVED INT,
  DAY_SERVED INT,
  DISCONTINUED BOOLEAN,
  IMAGE_SRC VARCHAR(250)
);